language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - "yarn lint:js"
  - "yarn test-cov"
  - "yarn codecov"

notifications:
  email:
    - ram@hiddentao.com
