language: node_js

branches:
  except:
    # qa and master will be built on CircleCI
    - qa
    - master

git:
  depth: 1

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - "yarn lint:js"
  - "yarn test-cov"
  - "yarn codecov"

notifications:
  email:
    - ram@hiddentao.com
