build_environment: &build_environment
  environment:
    ANDROID_HOME: "/usr/local/opt/android-sdk"
  macos:
    xcode: "9.4.0"
  working_directory: ~/repo


version: 2
jobs:
  prepare:
    <<: *build_environment
    steps:
      - checkout

      # Install basic deps
      - restore_cache:
          keys:
            - v1-dependencies-homebrew

      - run: brew install node@8
      - run: brew install yarn
      - run: brew install ruby

      - save_cache:
          paths:
            - /usr/local/Cellar
          key: v1-dependencies-homebrew

      # Setup and build app
      - restore_cache:
          keys:
          - v2-dependencies-npm-{{ checksum "package.json" }}

      - run: echo $CIRCLE_BRANCH
      - run: mkdir -p ~/.gradle
      - run: echo -e "METH_RELEASE_KEYSTORE_PASSWORD=$ANDROID_KEYSTORE_PASSWORD" >> ~/.gradle/gradle.properties
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without development
      - run: yarn

      - save_cache:
          paths:
            - ~/.yarn
            - ~/.cache/yarn
            - node_modules
            - vendor/bundle
            - ~/Library/Caches/CocoaPods
          key: v2-dependencies-npm-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths: .

  setup_qa:
    <<: *build_environment
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn setup:qa



workflows:
  version: 2
  qa:
    jobs:
      - prepare
      - setup_qa:
          requires:
            - prepare
