# To be enabled once mobile builds are needed
# version: 2
# jobs:
#   build-and-test:
#     macos:
#       xcode: "9.0"
#     steps:
#       - checkout
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: Install dependencies
#           command: yarn
#       - save_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: Run tests
#           command: yarn test
