build_environment: &build_environment
  environment:
    ANDROID_HOME: /usr/local/share/android-sdk
  macos:
    xcode: "9.4.0"
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *build_environment
    branches:
      only:
        - qa
    steps:
      - run: echo $CIRCLE_BRANCH

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-homebrew
      - run: brew install node@8
      - run: brew install yarn
      - run: brew install ruby
      - run: build-tools/scripts/ci-install-android-sdk
      - save_cache:
          paths:
            - /usr/local/Cellar
          key: v1-dependencies-homebrew

      - restore_cache:
          keys:
          - v1-dependencies-yarn-{{ checksum "package.json" }}-{{ checksum "Gemfile" }}

      # Install deps
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without development
      - run: yarn

      - save_cache:
          key: v1-dependencies-yarn-{{ checksum "package.json" }}-{{ checksum "Gemfile" }}
          paths:
            - ~/.yarn
            - ~/.cache/yarn
            - node_modules
            - vendor/bundle

      - restore_cache:
          keys:
            - v1-android-{{ checksum "android/app/build.gradle" }}
            - v1-ios-{{ checksum "ios/Podfile" }}

      # passswords/keys/etc
      - run: mkdir -p ~/.gradle
      - run: echo -e "METH_RELEASE_KEYSTORE_PASSWORD=$ENCRYPTION_KEY" >> ~/.gradle/gradle.properties
      - run: openssl aes-256-cbc -d -in build-tools/.config/testFairy.json.aes256 -out build-tools/.config/testFairy.json -pass pass:$ENCRYPTION_KEY

      - run: /bin/sh -c 'if [ \"$CIRCLE_BRANCH\" = \"qa\" ]; then yarn setup:qa; else echo "Skipping QA build"; fi'

      - save_cache:
          key: v1-ios-{{ checksum "ios/Podfile" }}
          paths:
            - ~/Library/Caches/CocoaPods
            - ios/Pods

      - run: yarn publish:android-beta

      - save_cache:
          key: v1-android-{{ checksum "android/app/build.gradle" }}
          paths:
            - ~/.gradle

      # See https://discuss.circleci.com/t/running-script-cp-embed-pods-frameworks-not-running-and-time-out/11791/7
      - run: yarn fastlane match --readonly appstore
      - run: "security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k circle circle.keychain"

      - run: yarn publish:ios-beta

      - run: yarn publish:desktop-beta
