build_environment: &build_environment
  environment:
    ANDROID_HOME: "/usr/local/opt/android-sdk"
  macos:
    xcode: "9.4.0"
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *build_environment
    branches:
      only:
        - qa
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-homebrew
      - run: brew install node@8
      - run: brew install yarn
      - run: brew install ruby
      - save_cache:
          paths:
            - /usr/local/Cellar
          key: v1-dependencies-homebrew

      - checkout

      # Setup and build app
      - restore_cache:
          keys:
          - v2-dependencies-npm-{{ checksum "package.json" }}

      - run: echo $CIRCLE_BRANCH
      - run: mkdir -p ~/.gradle
      - run: echo -e "METH_RELEASE_KEYSTORE_PASSWORD=$ANDROID_KEYSTORE_PASSWORD" >> ~/.gradle/gradle.properties
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without development
      - run: yarn

      - save_cache:
          paths:
            - ~/.yarn
            - ~/.cache/yarn
            - node_modules
            - vendor/bundle
            - ~/Library/Caches/CocoaPods
          key: v2-dependencies-npm-{{ checksum "package.json" }}

      - run: /bin/sh -c 'if [ \"$CIRCLE_BRANCH\" = \"qa\" ]; then yarn setup:qa; else yarn setup:prod; fi'
